# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

manipulator_controller:
  ros__parameters:
    joints:
      - 1-joint
      - 2-joint
      - 3-joint
      - 4-joint
      - 5-joint
      - 6-joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
